cacheFolder: ../.cache/yarn-cache

nodeLinker: node-modules

npmRegistryServer: "https://mavtek-840225427682.d.codeartifact.us-east-1.amazonaws.com/npm/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-aws-codeartifact.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-aws-codeartifact/v0.8.0/bundles/@yarnpkg/plugin-aws-codeartifact.js"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
